# Generated by Django 3.1 on 2020-08-12 06:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Project_Leader', models.CharField(blank=True, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, max_length=30, null=True)),
                ('Funding_Agency', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_And_time', models.DateTimeField(auto_now_add=True)),
                ('Picture', models.ImageField(blank=True, default='', null=True, upload_to='Project/Completed')),
            ],
            options={
                'ordering': ['date_And_time'],
            },
        ),
        migrations.CreateModel(
            name='Ongoing',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Project_Leader', models.CharField(blank=True, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, max_length=30, null=True)),
                ('Funding_Agency', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_And_time', models.DateTimeField(auto_now_add=True)),
                ('Picture', models.ImageField(blank=True, default='', null=True, upload_to='Project/Ongoing')),
            ],
            options={
                'ordering': ['date_And_time'],
            },
        ),
    ]
