# Generated by Django 3.1 on 2020-08-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('advisorId', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=50)),
                ('facebookId', models.URLField(blank=True, max_length=50, null=True)),
                ('instagramId', models.URLField(blank=True, max_length=50, null=True)),
                ('linkedIn', models.URLField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(upload_to='About/Advisor')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'Full_Name'],
            },
        ),
        migrations.CreateModel(
            name='Donars_and_partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeOfMember', models.CharField(max_length=150)),
                ('Full_Name', models.CharField(max_length=50)),
                ('facebookId', models.URLField(blank=True, max_length=50, null=True)),
                ('instagramId', models.URLField(blank=True, max_length=50, null=True)),
                ('linkedIn', models.URLField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(upload_to='About/Team')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'TypeOfMember'],
            },
        ),
        migrations.CreateModel(
            name='Image_multiple_Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Donars/image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='About.donars_and_partners')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
