# Generated by Django 3.1 on 2020-08-12 06:56

import Resources.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Resource',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Poster_Resource',
            fields=[
                ('PosterId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to=Resources.models.user_directory_path)),
                ('Heading', models.CharField(max_length=200)),
                ('publicationYear', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Resource_Video',
            fields=[
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Poster_multiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='resource/Poster')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.poster_resource')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Image_multiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resource/image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resources.image_resource')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
