# Generated by Django 3.1 on 2020-08-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Report',
        ),
    ]
